# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CanvasExamplePlugin
                                 A QGIS plugin
 Example plugin for QgsMapCanvas issues
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-06-21
        copyright            : (C) 2020 by Ciaran Evans
        email                : me@me.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load CanvasExamplePlugin class from file CanvasExamplePlugin.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .canvas_example import CanvasExamplePlugin
    return CanvasExamplePlugin(iface)
